### ISSUE TITLE
crash after arbitrary time due to issue with net data

### ISSUE THREAD

**Issue by SanFranciscoSunrise** [cjbassi/gotop#150]
Required information:

- gotop version (`gotop -1.5.1`):
```
gotop-1.5.1
```

- The output of `uname -a`: 
```
Linux localhost 4.14.78-gentoo #9 SMP Wed Apr 10 11:49:46 MST 2019 x86_64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz GenuineIntel GNU/Linux
```

- Terminal emulator (e.g. iTerm or gnome terminal): 
```
xfce
```
- Any relevenat hardware info: 
- tmux version if using tmux: none (do i need this for gotop?)

Also please copy or attach `~/.local/state/gotop/errors.log` if it exists and contains logs:

```
Error caught. Exiting program.

Issue with net data.

Diagnostics:
curRecvTotal: 146810441962
curSentTotal: 7069679236
self.prevRecvTotal: 146810240417
self.prevSentTotal: 7080931308
recvRecent: 201545
sentRecent: 18446744073698299544
int(recvRecent): 201545
int(sentRecent): -11252072

panic: 1

goroutine 12 [running]:
github.com/cjbassi/gotop/src/utils.Error(0x595a5b, 0x8, 0xc00039e000, 0xda)
	src/utils/utils.go:63 +0x23f
github.com/cjbassi/gotop/src/widgets.(*Net).update(0xc00000d2a0)
	src/widgets/net.go:62 +0x4f7
github.com/cjbassi/gotop/src/widgets.NewNet.func1(0xc000112820, 0xc00000d2a0)
	src/widgets/net.go:39 +0x5c
created by github.com/cjbassi/gotop/src/widgets.NewNet
	src/widgets/net.go:37 +0x28f
```

**Comment by cjbassi** [comment]
This has been fixed in the latest version. Feel free to reopen if it still occurs after updating.
