### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by shyim** [cjbassi/gotop#22]
Kernel: Linux resilio 4.13.16-1-pve #1 SMP PVE 4.13.16-45 (Wed, 28 Mar 2018 15:47:11 +0200) x86_64 GNU/Linux
Bash, Terminal Emulator: ITerm
Latest version from github
OS: Debian 9.4

```bash
Error caught. Exiting program.

Issue with table rows.

Diagnostics:
rowNum: -1
self.TopRow: -1
len(self.Rows): 15
self.Y: 17

panic: 1

goroutine 25 [running]:
github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui.Error(0x585ac3, 0xa, 0xc420720100, 0x38)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui/utils.go:35 +0x23f
github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui.(*Table).Buffer(0xc4200a6210, 0x0)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui/table.go:79 +0x8da
github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui.(*Grid).Buffer(0xc420059a40, 0x58e448)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui/grid.go:53 +0xbc
github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui.Render.func1(0xc420235330, 0x5a16e0, 0xc420059a40)
	/home/cjbassi/go/src/github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui/render.go:23 +0x76
created by github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui.Render
	/home/cjbassi/go/src/github.com/cjbassi/gotop/vendor/github.com/cjbassi/termui/render.go:21 +0xa7
```

**Comment by cjbassi** [comment]
Hi, can you download the latest release and tell me if you're still getting the issue? Thanks.

**Comment by shyim** [comment]
It works. Thank you :heart:
