### ISSUE TITLE
Panic due to net data when running KVM

### ISSUE THREAD

**Issue by auyer** [cjbassi/gotop#62]
This issue occurred when running or stopping a libvirt KVM. 

Please give the following info:

- The output of `uname -a`: Linux 4.18.9-1-MANJARO 
- Any relevenat hardware info: R7 2700x, AMD Vega 64, Radeon HD 7570
- Terminal shell (like zsh or bash): Bash
- Terminal emulator (like iTerm or gnome terminal): Termite
- tmux version if using tmux:

```
Error caught. Exiting program.

Issue with net data.

Diagnostics:
curRecvTotal: 533263535
curSentTotal: 494781200
self.prevRecvTotal: 552006946
self.prevSentTotal: 966066855
recvRecent: 18446744073690808205
sentRecent: 18446744073238265961
int(recvRecent): -18743411
int(sentRecent): -471285655

panic: 1

goroutine 5 [running]:
github.com/cjbassi/gotop/src/utils.Error(0x594890, 0x8, 0xc00054a000, 0xe4)
	/home/cjbassi/playground/gotop/src/utils/utils.go:63 +0x23f
github.com/cjbassi/gotop/src/widgets.(*Net).update(0xc00000c060)
	/home/cjbassi/playground/gotop/src/widgets/net.go:62 +0x4f7
github.com/cjbassi/gotop/src/widgets.NewNet.func1(0xc0001fa0f0, 0xc00000c060)
	/home/cjbassi/playground/gotop/src/widgets/net.go:39 +0x5c
created by github.com/cjbassi/gotop/src/widgets.NewNet
	/home/cjbassi/playground/gotop/src/widgets/net.go:37 +0x28f

```

**Comment by cjbassi** [comment]
This should be fixed with c7171781c13f2bdd2f3cffd149800426a97dd4c2. Let me know if you still get issues.
