### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Alumniminium** [cjbassi/gotop#76]
```
Error caught. Exiting program.
Issue with net data.
Diagnostics:
curRecvTotal: 13388292229
curSentTotal: 220381466
self.prevRecvTotal: 13829171955
self.prevSentTotal: 225848092
recvRecent: 18446744073268671890
sentRecent: 18446744073704084990
int(recvRecent): -440879726
int(sentRecent): -5466626
panic: 1
goroutine 19 [running]:
github.com/cjbassi/gotop/src/utils.Error(0x5948f6, 0x8, 0xc0001da000, 0xe7)
        /home/cjbassi/playground/gotop/src/utils/utils.go:63 +0x23f
github.com/cjbassi/gotop/src/widgets.(*Net).update(0xc0001a0020)
        /home/cjbassi/playground/gotop/src/widgets/net.go:62 +0x4f7
github.com/cjbassi/gotop/src/widgets.NewNet.func1(0xc0001960f0, 0xc0001a0020)
        /home/cjbassi/playground/gotop/src/widgets/net.go:39 +0x5c
created by github.com/cjbassi/gotop/src/widgets.NewNet
        /home/cjbassi/playground/gotop/src/widgets/net.go:37 +0x28f

```

**Comment by cjbassi** [comment]
This was just fixed with c7171781c13f2bdd2f3cffd149800426a97dd4c2.
