### ISSUE TITLE
Crashes on FreeBSD 12

### ISSUE THREAD

**Issue by yurivict** [cjbassi/gotop#84]
Hi again,

I tested it on FreeBSD 11.2 and it works there, but it fails on FreeBSD 12 amd64:

```
$ gotop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x521937]

goroutine 9 [running]:
github.com/cjbassi/gotop/src/widgets.(*Mem).update(0xc000011b60)
	/usr/ports/sysutils/gotop/work/gotop-1.7.0-4-gf608f63_GH0/src/github.com/cjbassi/gotop/src/widgets/mem.go:50 +0x1b7
github.com/cjbassi/gotop/src/widgets.NewMem(0x3b9aca00, 0x7, 0x0)
	/usr/ports/sysutils/gotop/work/gotop-1.7.0-4-gf608f63_GH0/src/github.com/cjbassi/gotop/src/widgets/mem.go:28 +0x284
main.initWidgets.func2(0xc0000172a0)
	/usr/ports/sysutils/gotop/work/gotop-1.7.0-4-gf608f63_GH0/src/github.com/cjbassi/gotop/main.go:214 +0x39
created by main.initWidgets
	/usr/ports/sysutils/gotop/work/gotop-1.7.0-4-gf608f63_GH0/src/github.com/cjbassi/gotop/main.go:213 +0x94
```

**Comment by cjbassi** [comment]
Just pushed a change to master that should hopefully fix the issue, assuming that the issue was caused by a mishandled error being returned from the memory usage function.

**Comment by yurivict** [comment]
~/.config/gotop/errors.log is:
```
21:15:06 temp_other.go:16: failed to get sensors from gopsutil: not implemented yet
21:15:06 mem.go:47: failed to get swap memory info from gopsutil: xswdev version mismatch
21:15:59 temp_other.go:16: failed to get sensors from gopsutil: not implemented yet
21:15:59 mem.go:47: failed to get swap memory info from gopsutil: xswdev version mismatch
```

**Comment by jbeich** [comment]
Probably caused by `dev_t` upgrade from `uint32_t` to `uint64_t` when [ino64](https://github.com/freebsd/freebsd/commit/e75ba1d5c4c79
) landed, affecting at least the size of `struct xswdev`.
https://github.com/shirou/gopsutil/blob/cce2d16538b4/mem/mem_freebsd.go#L90-L97

**Comment by yurivict** [comment]
The update fixed the problem.
Thank you!
